🐛 Fix pnpm v7 and typescript compatibility issues
```
pnpm add -DE @types/testing-library__jest-dom@5.14.5
```

https://github.com/pnpm/pnpm/discussions/4723

ERROR in src/App.test.tsx:8:23
TS2339: Property 'toBeInTheDocument' does not exist on type 'JestMatchers<HTMLElement>'.